### **1. Trasformare cicli in list comprehension**

Fai tre esempi di cicli producono una lista e poi riscrivi lo stesso codice usando la list comprehension

In [1]:
#1
lista1, lista2, lista3 = [], [], []

for i in range(10):
    lista1.append(i)

for i in "banana":
    lista2.append(i)

for i in range(10):
    if i % 2 == 0:
        lista3.append(True)
    else:
        lista3.append(False)

print(lista1)
print(lista2)
print(lista3)

# Parte 2

lista4 = [i for i in range(10)]
lista5 = [i for i in "banana"]
lista6 = [True if i % 2 == 0 else False for i in range(10)]

print(lista1 == lista4)
print(lista2 == lista5)
print(lista3 == lista6)








[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
['b', 'a', 'n', 'a', 'n', 'a']
[True, False, True, False, True, False, True, False, True, False]
True
True
True


### **2. Vettore di Numeri Primi**

1. **Crea un vettore** contenente tutti i numeri primi compresi tra **0 e 10**  
   _(Puoi scriverli direttamente nell'array)._

2. **Conta quanti numeri ci sono nel vettore** utilizzando la funzione `len()`.  **Ottieni lo stesso numero** accedendo all'attributo `.size` del vettore.

3. Quale pensi sia il tipo di dato (`dtype`) del vettore?  Prova a rispondere senza eseguire il codice e Verifica la tua risposta accedendo all'attributo `.dtype` del vettore

4. Scrivi l'array usando una list comprehension che controlla che i numeri siano primi. 

In [2]:
import numpy as np

primi = np.array([2, 3, 5, 7])
print(len(primi))
print(primi.size)
print(primi.dtype)


def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False
    return True

primi = np.array([n for n in range(11) if is_prime(n)])
print(primi)

4
4
int64
[2 3 5 7]


### **3.  Operazioni su array**
Crea un array **a**, 1D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente una sottostringa a piacere e **c** che è il reverse dell'array **a** (esempio [1,2,3] diventa [3,2,1]) .  Dividi l'array **a** per l'array **c**. Fai la stessa cosa per una lista.

In [3]:
a = np.arange(1,6)
b = np.array([i for i in "cristiano"])
c = np.flip(a)

print(a)
print(b)
print(c)
print(a / c)

a = list(range(1,6))
b = [i for i in "cristiano"]
c = a[::-1]

print(a)
print(b)
print(c)

divisione = [a/b for a,b in zip(a,c)]
print(divisione)







[1 2 3 4 5]
['c' 'r' 'i' 's' 't' 'i' 'a' 'n' 'o']
[5 4 3 2 1]
[0.2 0.5 1.  2.  5. ]
[1, 2, 3, 4, 5]
['c', 'r', 'i', 's', 't', 'i', 'a', 'n', 'o']
[5, 4, 3, 2, 1]
[0.2, 0.5, 1.0, 2.0, 5.0]
